export type SeedSatellite = {
  slug: string;
  name: string;
  noradId?: string;
  agency: string;
  country: string;
  category: string;
  missionType: string;
  description: string;
  shortDescription: string;
  launchDate: string;
  orbitType: string;
  altitude?: string;
  inclination?: string;
  facts: string[];
  timeline: { date: string; title: string }[];
  relatedSlugs?: string[];
  featured?: boolean;
  feedPriority?: number;
  model?: {
    fallbackType: string;
    attribution: string;
    embedUid?: string;
    sourceUrl?: string;
    commercialUseAllowed?: boolean;
    modificationAllowed?: boolean;
  };
};

export const SEED_SATELLITES: SeedSatellite[] = [
  {
    slug: "iss",
    name: "International Space Station",
    noradId: "25544",
    agency: "NASA / Roscosmos / ESA / JAXA / CSA",
    country: "International",
    category: "iss",
    missionType: "Crewed space station",
    shortDescription: "Humanity's home in low Earth orbit.",
    description:
      "The ISS is a modular space station in low Earth orbit. Crews conduct science, test life-support systems, and demonstrate technologies for future deep-space missions.",
    launchDate: "1998 (assembly ongoing)",
    orbitType: "LEO",
    altitude: "~420 km",
    inclination: "51.6°",
    featured: true,
    feedPriority: 100,
    facts: [
      "Orbits Earth roughly every 90 minutes.",
      "Often visible to the naked eye at dawn and dusk.",
      "Hosts hundreds of microgravity experiments.",
    ],
    timeline: [
      { date: "1998", title: "First module Zarya launched" },
      { date: "2000", title: "First permanent crew arrives" },
    ],
    relatedSlugs: ["hubble", "starlink-1007"],
    model: {
      fallbackType: "procedural-station",
      attribution: "Procedural ISS-style model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "hubble",
    name: "Hubble Space Telescope",
    noradId: "20580",
    agency: "NASA / ESA",
    country: "USA",
    category: "science",
    missionType: "Space telescope",
    shortDescription: "Iconic observatory imaging the universe.",
    description:
      "Hubble observes the cosmos in visible and ultraviolet light from low Earth orbit, delivering iconic deep-field and nebula images.",
    launchDate: "1990-04-24",
    orbitType: "LEO",
    altitude: "~540 km",
    inclination: "28.5°",
    featured: true,
    feedPriority: 90,
    facts: ["Serviced by Space Shuttle missions.", "Helped refine the age of the universe."],
    timeline: [{ date: "1990", title: "Launched aboard Discovery" }],
    relatedSlugs: ["iss"],
    model: {
      fallbackType: "science-observatory",
      attribution: "Procedural observatory model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "starlink-1007",
    name: "Starlink-1007",
    noradId: "44713",
    agency: "SpaceX",
    country: "USA",
    category: "starlink",
    missionType: "Broadband constellation",
    shortDescription: "Part of SpaceX's global internet constellation.",
    description:
      "Starlink satellites provide broadband internet from low Earth orbit using phased-array antennas and laser inter-satellite links on newer batches.",
    launchDate: "2019+",
    orbitType: "LEO",
    altitude: "~550 km",
    featured: true,
    feedPriority: 85,
    facts: ["Starlink trains can appear as a string of lights after launch.", "Thousands of satellites are planned."],
    timeline: [{ date: "2019", title: "First operational Starlink launch" }],
    relatedSlugs: ["iss"],
    model: {
      fallbackType: "procedural-flat-sat",
      attribution: "Procedural flat-panel satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "chandrayaan-3",
    name: "Chandrayaan-3 Mission",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Lunar exploration",
    shortDescription: "India's successful lunar south-pole landing mission.",
    description:
      "Chandrayaan-3 demonstrated soft landing near the lunar south pole and deployed the Pragyan rover to study the surface.",
    launchDate: "2023-07-14",
    orbitType: "Lunar transfer",
    featured: true,
    feedPriority: 95,
    facts: ["Made India the fourth nation to land on the Moon.", "Studied lunar regolith and thermophysical properties."],
    timeline: [
      { date: "2023-07", title: "Launched on LVM3" },
      { date: "2023-08", title: "Vikram lander touched down" },
    ],
    relatedSlugs: ["mangalyaan", "insat-3dr"],
    model: {
      fallbackType: "lunar-orbiter",
      attribution: "Procedural lunar mission model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "mangalyaan",
    name: "Mangalyaan (MOM)",
    noradId: "40269",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Mars orbiter",
    shortDescription: "India's first interplanetary mission.",
    description:
      "The Mars Orbiter Mission studied the Martian atmosphere and surface from orbit, demonstrating cost-effective interplanetary capability.",
    launchDate: "2013-11-05",
    orbitType: "Mars orbit",
    featured: true,
    feedPriority: 80,
    facts: ["First Asian nation to reach Mars orbit.", "Carried a color camera and methane sensor."],
    timeline: [{ date: "2014-09", title: "Entered Mars orbit" }],
    relatedSlugs: ["chandrayaan-3"],
    model: {
      fallbackType: "planetary-orbiter",
      attribution: "Procedural planetary orbiter · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "insat-3dr",
    name: "INSAT-3DR",
    noradId: "41752",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Weather & search-and-rescue",
    shortDescription: "Advanced weather satellite over India.",
    description:
      "INSAT-3DR provides weather imaging, meteorological data, and search-and-rescue relay services for the Indian region.",
    launchDate: "2016-09-08",
    orbitType: "GEO",
    altitude: "~35,786 km",
    feedPriority: 70,
    facts: ["Improves cyclone tracking over the Indian Ocean.", "Supports disaster response communications."],
    timeline: [{ date: "2016", title: "Placed in geostationary orbit" }],
    model: {
      fallbackType: "geo-comms",
      attribution: "Procedural GEO weather model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "cartosat-2",
    name: "Cartosat-2",
    noradId: "29710",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Earth observation",
    shortDescription: "High-resolution imaging for mapping.",
    description: "Cartosat-2 series satellites capture panchromatic imagery used for cartography, urban planning, and resource monitoring.",
    launchDate: "2007-01-10",
    orbitType: "LEO",
    feedPriority: 65,
    facts: ["Sub-meter class imaging capability.", "Supports national mapping programs."],
    timeline: [{ date: "2007", title: "First Cartosat-2 launch" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural imaging satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "risat-2b",
    name: "RISAT-2B",
    noradId: "44354",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Radar imaging",
    shortDescription: "All-weather SAR Earth observation.",
    description: "RISAT-2B uses synthetic aperture radar to image Earth through clouds and at night.",
    launchDate: "2019-05-22",
    orbitType: "LEO",
    feedPriority: 60,
    facts: ["Radar can see through cloud cover.", "Useful for agriculture and disaster monitoring."],
    timeline: [{ date: "2019", title: "Launched on PSLV" }],
    model: {
      fallbackType: "radar-sat",
      attribution: "Procedural SAR model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "oceansat-2",
    name: "Oceansat-2",
    noradId: "35931",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Ocean monitoring",
    shortDescription: "Monitors ocean color and surface winds.",
    description: "Oceansat-2 supports fisheries, climate studies, and weather forecasting with ocean-color and scatterometer payloads.",
    launchDate: "2009-09-23",
    orbitType: "LEO",
    feedPriority: 55,
    facts: ["Helps track phytoplankton blooms.", "Scatterometer data aids cyclone forecasting."],
    timeline: [{ date: "2009", title: "Operational ocean mission begins" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural ocean satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "resourcesat-2a",
    name: "Resourcesat-2A",
    noradId: "41882",
    agency: "ISRO",
    country: "India",
    category: "isro",
    missionType: "Resource monitoring",
    shortDescription: "Multi-spectral land and water monitoring.",
    description: "Resourcesat-2A provides multispectral data for agriculture, forestry, and water resource management.",
    launchDate: "2016-12-07",
    orbitType: "LEO",
    feedPriority: 50,
    facts: ["Three sensors cover different resolutions.", "Data supports crop health mapping."],
    timeline: [{ date: "2016", title: "Launched on PSLV" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural resource satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "navic-irnss-1i",
    name: "NavIC (IRNSS-1I)",
    noradId: "43441",
    agency: "ISRO",
    country: "India",
    category: "navigation",
    missionType: "Regional navigation",
    shortDescription: "India's regional GPS alternative.",
    description:
      "The Indian Regional Navigation Satellite System provides positioning services over India and surrounding regions.",
    launchDate: "2018-04-12",
    orbitType: "GEO / GSO",
    feedPriority: 75,
    facts: ["Seven-satellite constellation design.", "Improves positioning accuracy for civilian users."],
    timeline: [{ date: "2018", title: "IRNSS-1I operational" }],
    model: {
      fallbackType: "navigation-sat",
      attribution: "Procedural navigation satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "landsat-9",
    name: "Landsat 9",
    noradId: "49260",
    agency: "NASA / USGS",
    country: "USA",
    category: "nasa",
    missionType: "Earth observation",
    shortDescription: "Long-running land imaging program.",
    description: "Landsat 9 continues decades of continuous Earth surface imaging for climate, agriculture, and urban studies.",
    launchDate: "2021-09-27",
    orbitType: "LEO",
    featured: true,
    feedPriority: 72,
    facts: ["Data is free and open.", "Sun-synchronous orbit enables consistent lighting."],
    timeline: [{ date: "2021", title: "Launched from Vandenberg" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural Landsat-style model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "goes-18",
    name: "GOES-18",
    noradId: "51850",
    agency: "NOAA / NASA",
    country: "USA",
    category: "weather",
    missionType: "Weather monitoring",
    shortDescription: "Geostationary weather sentinel for the Americas.",
    description: "GOES-18 provides real-time weather imagery, lightning mapping, and space weather monitoring.",
    launchDate: "2022-03-01",
    orbitType: "GEO",
    feedPriority: 68,
    facts: ["Images update every few minutes in mesoscale mode.", "Helps track hurricanes and wildfires."],
    timeline: [{ date: "2022", title: "Declared operational GOES-West" }],
    model: {
      fallbackType: "geo-comms",
      attribution: "Procedural weather satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "noaa-20",
    name: "NOAA-20 (JPSS-1)",
    noradId: "43013",
    agency: "NOAA / NASA",
    country: "USA",
    category: "weather",
    missionType: "Polar weather",
    shortDescription: "Polar-orbiting weather and climate data.",
    description: "NOAA-20 carries instruments for atmospheric profiling, ozone monitoring, and global weather forecasting.",
    launchDate: "2017-11-18",
    orbitType: "LEO",
    feedPriority: 62,
    facts: ["Part of the JPSS program.", "Feeds numerical weather prediction models."],
    timeline: [{ date: "2017", title: "Launched on Delta II" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural polar weather satellite · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
  {
    slug: "sentinel-2a",
    name: "Sentinel-2A",
    noradId: "40697",
    agency: "ESA",
    country: "Europe",
    category: "scientific",
    missionType: "Copernicus imaging",
    shortDescription: "High-repeat multispectral Earth imaging.",
    description: "Sentinel-2A delivers optical imagery for agriculture, forests, and land-cover change under the Copernicus program.",
    launchDate: "2015-06-23",
    orbitType: "LEO",
    feedPriority: 58,
    facts: ["Revisits the same area every five days with twin satellites.", "13 spectral bands."],
    timeline: [{ date: "2015", title: "First Sentinel-2 launch" }],
    model: {
      fallbackType: "earth-observer",
      attribution: "Procedural Copernicus-style model · OrbytMax",
      commercialUseAllowed: true,
      modificationAllowed: true,
    },
  },
];

export const EDUCATION_PAGES = [
  {
    slug: "parts-of-a-satellite",
    title: "Parts of a Satellite",
    agency: "OrbytMax",
    summary: "Learn what solar panels, antennas, payloads, and thrusters do.",
    bodyJson: JSON.stringify({
      sections: [
        { title: "Solar panels", text: "Convert sunlight into electricity." },
        { title: "Antennas", text: "Send and receive data with Earth." },
        { title: "Payload", text: "The mission instruments that collect science or images." },
        { title: "Thrusters", text: "Small engines that adjust orbit and orientation." },
      ],
    }),
    modelKey: "generic",
    featured: true,
  },
  {
    slug: "isro-missions",
    title: "ISRO Mission Library",
    agency: "ISRO",
    summary: "Explore Indian Earth observation, navigation, and planetary missions.",
    featured: true,
  },
  {
    slug: "nasa-missions",
    title: "NASA & Global Missions",
    agency: "NASA",
    summary: "From Hubble to Landsat — key missions that changed how we see Earth and space.",
    featured: true,
  },
];

export const QUIZ_SEED = {
  slug: "orbit-basics",
  title: "Orbit Basics Quiz",
  description: "Quick check on LEO, GEO, and what TLE data means.",
  questions: [
    {
      question: "Which orbit is closest to Earth?",
      options: ["LEO", "GEO", "HEO"],
      correctIndex: 0,
      explanation: "Low Earth Orbit (LEO) is typically below 2,000 km altitude.",
    },
    {
      question: "What does TLE data help estimate?",
      options: ["Satellite color", "Satellite position over time", "Launch cost"],
      correctIndex: 1,
      explanation: "Two-line element sets are used to estimate where a satellite is now and next.",
    },
    {
      question: "GEO satellites appear to stay over one spot because they orbit at about:",
      options: ["400 km", "35,786 km", "1,000,000 km"],
      correctIndex: 1,
      explanation: "Geostationary orbit matches Earth's rotation at ~35,786 km.",
    },
  ],
};
